EYE_LOOK_IN_LEFT = "eyeLookIn_L"
EYE_LOOK_OUT_LEFT = "eyeLookOut_L"
EYE_LOOK_DOWN_LEFT = "eyeLookDown_L"
EYE_LOOK_UP_LEFT = "eyeLookUp_L"
EYE_BLINK_LEFT = "eyeBlink_L"
EYE_SQUINT_LEFT = "eyeSquint_L"
EYE_WIDE_LEFT = "eyeWide_L"
EYE_LOOK_IN_RIGHT = "eyeLookIn_R"
EYE_LOOK_OUT_RIGHT = "eyeLookOut_R"
EYE_LOOK_DOWN_RIGHT = "eyeLookDown_R"
EYE_LOOK_UP_RIGHT = "eyeLookUp_R"
EYE_BLINK_RIGHT = "eyeBlink_R"
EYE_SQUINT_RIGHT = "eyeSquint_R"
EYE_WIDE_RIGHT = "eyeWide_R"
BROW_DOWN_LEFT = "browDown_L"
BROW_OUTER_UP_LEFT = "browOuterUp_L"
BROW_DOWN_RIGHT = "browDown_R"
BROW_OUTER_UP_RIGHT = "browOuterUp_R"
BROW_INNER_UP = "browInnerUp"
NOSE_SNEER_LEFT = "noseSneer_L"
NOSE_SNEER_RIGHT = "noseSneer_R"
CHEEK_SQUINT_LEFT = "cheekSquint_L"
CHEEK_SQUINT_RIGHT = "cheekSquint_R"
CHEEK_PUFF = "cheekPuff"
MOUTH_LEFT = "mouthLeft"
MOUTH_DIMPLE_LEFT = "mouthDimple_L"
MOUTH_FROWN_LEFT = "mouthFrown_L"
MOUTH_LOWER_DOWN_LEFT = "mouthLowerDown_L"
MOUTH_PRESS_LEFT = "mouthPress_L"
MOUTH_SMILE_LEFT = "mouthSmile_L"
MOUTH_STRETCH_LEFT = "mouthStretch_L"
MOUTH_UPPER_UP_LEFT = "mouthUpperUp_L"
MOUTH_RIGHT = "mouthRight"
MOUTH_DIMPLE_RIGHT = "mouthDimple_R"
MOUTH_FROWN_RIGHT = "mouthFrown_R"
MOUTH_LOWER_DOWN_RIGHT = "mouthLowerDown_R"
MOUTH_PRESS_RIGHT = "mouthPress_R"
MOUTH_SMILE_RIGHT = "mouthSmile_R"
MOUTH_STRETCH_RIGHT = "mouthStretch_R"
MOUTH_UPPER_UP_RIGHT = "mouthUpperUp_R"
MOUTH_CLOSE = "mouthClose"
MOUTH_FUNNEL = "mouthFunnel"
MOUTH_PUCKER = "mouthPucker"
MOUTH_ROLL_LOWER = "mouthRollLower"
MOUTH_ROLL_UPPER = "mouthRollUpper"
MOUTH_SHRUG_LOWER = "mouthShrugLower"
MOUTH_SHRUG_UPPER = "mouthShrugUpper"
JAW_LEFT = "jawLeft"
JAW_RIGHT = "jawRight"
JAW_FORWARD = "jawForward"
JAW_OPEN = "jawOpen"
TONGUE_OUT = "tongueOut"

BLENDSHAPE_NAMES = [
    EYE_LOOK_IN_LEFT,  # 0
    EYE_LOOK_OUT_LEFT,  # 1
    EYE_LOOK_DOWN_LEFT,  # 2
    EYE_LOOK_UP_LEFT,  # 3
    EYE_BLINK_LEFT,  # 4
    EYE_SQUINT_LEFT,  # 5
    EYE_WIDE_LEFT,  # 6
    EYE_LOOK_IN_RIGHT,  # 7
    EYE_LOOK_OUT_RIGHT,  # 8
    EYE_LOOK_DOWN_RIGHT,  # 9
    EYE_LOOK_UP_RIGHT,  # 10
    EYE_BLINK_RIGHT,  # 11
    EYE_SQUINT_RIGHT,  # 12
    EYE_WIDE_RIGHT,  # 13
    BROW_DOWN_LEFT,  # 14
    BROW_OUTER_UP_LEFT,  # 15
    BROW_DOWN_RIGHT,  # 16
    BROW_OUTER_UP_RIGHT,  # 17
    BROW_INNER_UP,  # 18
    NOSE_SNEER_LEFT,  # 19
    NOSE_SNEER_RIGHT,  # 20
    CHEEK_SQUINT_LEFT,  # 21
    CHEEK_SQUINT_RIGHT,  # 22
    CHEEK_PUFF,  # 23
    MOUTH_LEFT,  # 24
    MOUTH_DIMPLE_LEFT,  # 25
    MOUTH_FROWN_LEFT,  # 26
    MOUTH_LOWER_DOWN_LEFT,  # 27
    MOUTH_PRESS_LEFT,  # 28
    MOUTH_SMILE_LEFT,  # 29
    MOUTH_STRETCH_LEFT,  # 30
    MOUTH_UPPER_UP_LEFT,  # 31
    MOUTH_RIGHT,  # 32
    MOUTH_DIMPLE_RIGHT,  # 33
    MOUTH_FROWN_RIGHT,  # 34
    MOUTH_LOWER_DOWN_RIGHT,  # 35
    MOUTH_PRESS_RIGHT,  # 36
    MOUTH_SMILE_RIGHT,  # 37
    MOUTH_STRETCH_RIGHT,  # 38
    MOUTH_UPPER_UP_RIGHT,  # 39
    MOUTH_CLOSE,  # 40
    MOUTH_FUNNEL,  # 41
    MOUTH_PUCKER,  # 42
    MOUTH_ROLL_LOWER,  # 43
    MOUTH_ROLL_UPPER,  # 44
    MOUTH_SHRUG_LOWER,  # 45
    MOUTH_SHRUG_UPPER,  # 46
    JAW_LEFT,  # 47
    JAW_RIGHT,  # 48
    JAW_FORWARD,  # 49
    JAW_OPEN,  # 50
    TONGUE_OUT,  # 51
]

EYE_LEFT_BLENDSHAPES = [
    EYE_LOOK_IN_LEFT,  # 0
    EYE_LOOK_OUT_LEFT,  # 1
    EYE_LOOK_DOWN_LEFT,  # 2
    EYE_LOOK_UP_LEFT,  # 3
    EYE_BLINK_LEFT,  # 4
    EYE_SQUINT_LEFT,  # 5
    EYE_WIDE_LEFT,  # 6
]

EYE_RIGHT_BLENDSHAPES = [
    EYE_LOOK_IN_RIGHT,  # 7
    EYE_LOOK_OUT_RIGHT,  # 8
    EYE_LOOK_DOWN_RIGHT,  # 9
    EYE_LOOK_UP_RIGHT,  # 10
    EYE_BLINK_RIGHT,  # 11
    EYE_SQUINT_RIGHT,  # 12
    EYE_WIDE_RIGHT,  # 13
]

BROW_LEFT_BLENDSHAPES = [
    BROW_DOWN_LEFT,  # 14
    BROW_OUTER_UP_LEFT,  # 15

]

BROW_RIGHT_BLENDSHAPES = [
    BROW_DOWN_RIGHT,  # 16
    BROW_OUTER_UP_RIGHT,  # 17

]

BROW_BOTH_BLENDSHAPES = [
    BROW_INNER_UP,  # 18
]

NOSE_BLENDSHAPES = [
    NOSE_SNEER_LEFT,  # 19
    NOSE_SNEER_RIGHT,  # 20
]

CHECK_BLENDSHAPES = [
    CHEEK_SQUINT_LEFT,  # 21
    CHEEK_SQUINT_RIGHT,  # 22
    CHEEK_PUFF,  # 23
]

MOUTH_LEFT_BLENDSHAPES = [
    MOUTH_LEFT,  # 24
    MOUTH_DIMPLE_LEFT,  # 25
    MOUTH_FROWN_LEFT,  # 26
    MOUTH_LOWER_DOWN_LEFT,  # 27
    MOUTH_PRESS_LEFT,  # 28
    MOUTH_SMILE_LEFT,  # 29
    MOUTH_STRETCH_LEFT,  # 30
    MOUTH_UPPER_UP_LEFT,  # 31
]

MOUTH_RIGHT_BLENDSHAPES = [
    MOUTH_RIGHT,  # 32
    MOUTH_DIMPLE_RIGHT,  # 33
    MOUTH_FROWN_RIGHT,  # 34
    MOUTH_LOWER_DOWN_RIGHT,  # 35
    MOUTH_PRESS_RIGHT,  # 36
    MOUTH_SMILE_RIGHT,  # 37
    MOUTH_STRETCH_RIGHT,  # 38
    MOUTH_UPPER_UP_RIGHT,  # 39
]

MOUTH_BOTH_BLENDSHAPES = [
    MOUTH_CLOSE,  # 40
    MOUTH_FUNNEL,  # 41
    MOUTH_PUCKER,  # 42
    MOUTH_ROLL_LOWER,  # 43
    MOUTH_ROLL_UPPER,  # 44
    MOUTH_SHRUG_LOWER,  # 45
    MOUTH_SHRUG_UPPER,  # 46
]

JAW_BLENDSHAPES = [
    JAW_LEFT,  # 47
    JAW_RIGHT,  # 48
    JAW_FORWARD,  # 49
    JAW_OPEN,  # 50
]

TONGUE_BLENDSHAPES = [
    TONGUE_OUT,  # 51
]

COLUMN_0_BLENDSHAPES = EYE_RIGHT_BLENDSHAPES + BROW_RIGHT_BLENDSHAPES + [NOSE_SNEER_RIGHT, CHEEK_SQUINT_RIGHT]
COLUMN_1_BLENDSHAPES = EYE_LEFT_BLENDSHAPES + BROW_LEFT_BLENDSHAPES + [NOSE_SNEER_LEFT, CHEEK_SQUINT_LEFT]
COLUMN_2_BLENDSHAPES = MOUTH_RIGHT_BLENDSHAPES + [JAW_RIGHT]
COLUMN_3_BLENDSHAPES = MOUTH_LEFT_BLENDSHAPES + [JAW_LEFT]
COLUMN_4_BLENDSHAPES = [BROW_INNER_UP, CHEEK_PUFF] + MOUTH_BOTH_BLENDSHAPES + [JAW_FORWARD, JAW_OPEN, TONGUE_OUT]

BLENDSHAPE_COLUMNS = [
    COLUMN_0_BLENDSHAPES,
    COLUMN_1_BLENDSHAPES,
    COLUMN_2_BLENDSHAPES,
    COLUMN_3_BLENDSHAPES,
    COLUMN_4_BLENDSHAPES,
]

RIGHT_EYE_ROTATION_X = "rightEyeRotationX"
RIGHT_EYE_ROTATION_Y = "rightEyeRotationX"
RIGHT_EYE_ROTATION_Z = "rightEyeRotationX"
RIGHT_EYE_ROTATIONS = [RIGHT_EYE_ROTATION_X, RIGHT_EYE_ROTATION_Y, RIGHT_EYE_ROTATION_Y]

LEFT_EYE_ROTATION_X = "leftEyeRotationX"
LEFT_EYE_ROTATION_Y = "leftEyeRotationY"
LEFT_EYE_ROTATION_Z = "leftEyeRotationZ"
LEFT_EYE_ROTATIONS = [LEFT_EYE_ROTATION_X, LEFT_EYE_ROTATION_Y, LEFT_EYE_ROTATION_Z]

HEAD_ROTATION_X = "headRotationX"
HEAD_ROTATION_Y = "headRotationY"
HEAD_ROTATION_Z = "headRotationZ"
HEAD_POSITION_X = "headPositionX"
HEAD_POSITION_Y = "headPositionY"
HEAD_POSITION_Z = "headPositionZ"
HEAD_ROTATIONS = [HEAD_ROTATION_X, HEAD_ROTATION_Y, HEAD_ROTATION_Z]
HEAD_POSITIONS = [HEAD_POSITION_X, HEAD_POSITION_Y, HEAD_POSITION_Z]

ROTATION_POSITION_NAMES = RIGHT_EYE_ROTATIONS + LEFT_EYE_ROTATIONS + HEAD_ROTATIONS + HEAD_POSITIONS
